---
title: "Curve Number"
author: "Alice Dambroz"
date: "2025-12-15"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(lubridate)
library(scales)
library(gridExtra)
library(dplyr)
library(effsize)
library(rstatix)
library(cowplot)
library(readr)
library(grid)

data = read.csv("/Users/alicedambroz/Desktop/03. Posdoc UMN/Discovery Farms/Alice Dambroz_RW1_Load_Files_12-12-2025/Plot_CN-nonfrozen.csv", header = T, sep = ",")
paired = read.csv("/Users/alicedambroz/Desktop/03. Posdoc UMN/Discovery Farms/Alice Dambroz_RW1_Load_Files_12-12-2025/Plot_CN-paired-nonfrozen.csv", header = T, sep = ",")
previous = read.csv("/Users/alicedambroz/Desktop/03. Posdoc UMN/Discovery Farms/Alice Dambroz_RW1_Load_Files_12-12-2025/Plot_CN-before-21.csv", header = T, sep = ",")
all_sites = read.csv("/Users/alicedambroz/Desktop/03. Posdoc UMN/Discovery Farms/All-sites-CN-nonfrozen.csv", header = T, sep = ",")
df_events = read.csv("/Users/alicedambroz/Downloads/RWN1_events_extended.csv", header = T, sep = ",") #RWS1_events_extended.csv



data$Site <- as.factor(data$Site)
paired$Site <- as.factor(paired$Site)
previous$Site <- as.factor(previous$Site)
all_sites$Site <- as.factor(all_sites$Site)
```

#Hydrographs all sites
```{r}
#Setting directory
output_dir <- "/Users/alicedambroz/Desktop/03. Posdoc UMN/Discovery Farms/Python-output" # Update this!
if (!dir.exists(output_dir)) dir.create(output_dir, recursive = TRUE)

df_events <- read_csv("/Users/alicedambroz/Desktop/03. Posdoc UMN/Discovery Farms/Python-output/All_Sites_Events_Plotting.csv")
df_events$Date <- ymd_hms(df_events$Date)

#Function for hydrographs
plot_rainfall_runoff <- function(df_event, event_id, site_name) {
  
  min_time <- min(df_event$Date, na.rm = TRUE)
  max_time <- max(df_event$Date, na.rm = TRUE)
  
  #Adding 'frozen' status
  frozen_status <- unique(df_event$Frozen)[1]
  
  #Adding information as title
  plot_title <- paste0("Site: ", site_name, " | Event: ", event_id, " | Condition: ", frozen_status)
  
  #Changing color for 'frozen' status
  title_color <- ifelse(tolower(frozen_status) == "frozen", "red", "black")

  #Rainfall
  g_rain <- ggplot(df_event, aes(x = Date)) +
    geom_bar(aes(y = Rainfall_mm), stat = 'identity', fill = "blue", width = 60) +
    scale_y_reverse(name = "Rainfall (mm)", expand = expansion(mult = c(0.1, 0))) +
    scale_x_datetime(limits = c(min_time, max_time), minor_breaks = "2 hours") +
    theme_light(base_size = 12) +
    theme(
      axis.title.x = element_blank(),
      axis.text.x = element_blank(),
      axis.ticks.x = element_blank(),
      axis.title.y = element_text(color = "blue", size = 10),
      axis.text.y = element_text(size = 8),
      plot.margin = margin(t = 10, r = 10, b = 0, l = 10),
      plot.title = element_text(color = title_color, face = "bold")
    ) +
    labs(title = plot_title)

  #Runoff
  g_flow <- ggplot(df_event, aes(x = Date)) +
    geom_line(aes(y = Volume_mm), color = "black", linewidth = 1) +
    scale_y_continuous(name = "Runoff Volume (mm)", limits = c(0, NA)) +
    scale_x_datetime(limits = c(min_time, max_time), date_labels = "%d/%m %H:%M", minor_breaks = "2 hours") +
    labs(x = "Date/Time") + 
    theme_light(base_size = 12) +
    theme(
      axis.title.y = element_text(size = 10),
      axis.text.y = element_text(size = 8),
      axis.text.x = element_text(angle = 45, hjust = 1),
      plot.margin = margin(t = 0, r = 10, b = 10, l = 10)
    )

  #Combine P and Q
  g_rain_grob <- ggplotGrob(g_rain)
  g_flow_grob <- ggplotGrob(g_flow)
  maxWidth <- grid::unit.pmax(g_rain_grob$widths[2:5], g_flow_grob$widths[2:5])
  g_rain_grob$widths[2:5] <- as.list(maxWidth)
  g_flow_grob$widths[2:5] <- as.list(maxWidth)
  
  combined_plot <- plot_grid(g_rain_grob, g_flow_grob, ncol = 1, rel_heights = c(1, 2), align = "v")
  return(combined_plot)
}

#Loop for hydrographs
#Plots per site and per event number
unique_pairs <- unique(df_events[, c("Site", "Event")])
unique_pairs <- unique_pairs[order(unique_pairs$Site, unique_pairs$Event), ]

pdf_path <- file.path(output_dir, "All_Sites_Hydrographs_Status.pdf")
print(paste("Generating PDF at:", pdf_path))

pdf(pdf_path, width = 10, height = 7)

for(i in 1:nrow(unique_pairs)) {
  current_site <- unique_pairs$Site[i]
  current_event <- unique_pairs$Event[i]
  
  df_subset <- df_events %>% 
    filter(Site == current_site, Event == current_event)
  
  if(nrow(df_subset) > 0) {
    p <- plot_rainfall_runoff(df_subset, current_event, current_site)
    print(p)
  }
}
dev.off()
print()
```



#Hydrographs per site
```{r}
#Data format
df_events$Date <- ymd_hms(df_events$Date) 

#Plot function
plot_rainfall_runoff <- function(df_event, event_id) {
  
  # Calculate limits to ensure both plots share the exact same X-axis
  min_time <- min(df_event$Date, na.rm = TRUE)
  max_time <- max(df_event$Date, na.rm = TRUE)
  
  #Rainfall
  g_rain <- ggplot(df_event, aes(x = Date)) +
    geom_bar(aes(y = Rainfall_mm), stat = 'identity', fill = "blue", width = 60) + #width=60 for 1-min data visibility
    scale_y_reverse(
      name = "Rainfall (mm)",
      expand = expansion(mult = c(0.1, 0)) #small buffer at top
    ) +
    scale_x_datetime(
      limits = c(min_time, max_time), 
      minor_breaks = "2 hours"
    ) +
    theme_light(base_size = 12) +
    theme(
      axis.title.x = element_blank(),
      axis.text.x = element_blank(),    #hide x-axis text for top plot
      axis.ticks.x = element_blank(),
      axis.title.y = element_text(color = "blue", size = 10),
      axis.text.y = element_text(size = 8),
      plot.margin = margin(t = 10, r = 10, b = 0, l = 10) #reduce bottom margin
    ) +
    labs(title = paste("Event ID:", event_id))

  #Runoff
  g_flow <- ggplot(df_event, aes(x = Date)) +
    geom_line(aes(y = Volume_mm), color = "black", linewidth = 1) +
    scale_y_continuous(
      name = "Runoff Volume (mm)", 
      limits = c(0, NA) #y-axis start at 0
    ) +
    scale_x_datetime(
      limits = c(min_time, max_time), 
      date_labels = "%d/%m %H:%M", 
      minor_breaks = "2 hours"
    ) +
    labs(x = "Date/Time") + 
    theme_light(base_size = 12) +
    theme(
      axis.title.y = element_text(size = 10),
      axis.text.y = element_text(size = 8),
      axis.text.x = element_text(angle = 45, hjust = 1), #angle x-axis text
      plot.margin = margin(t = 0, r = 10, b = 10, l = 10) #reduce top margin
    )

  # Align axes
  g_rain_grob <- ggplotGrob(g_rain)
  g_flow_grob <- ggplotGrob(g_flow)
  
  maxWidth <- grid::unit.pmax(g_rain_grob$widths[2:5], g_flow_grob$widths[2:5])
  g_rain_grob$widths[2:5] <- as.list(maxWidth)
  g_flow_grob$widths[2:5] <- as.list(maxWidth)
  
  #Combine P and Q 1:2 height
  combined_plot <- plot_grid(g_rain_grob, g_flow_grob, ncol = 1, rel_heights = c(1, 2), align = "v")
  
  return(combined_plot)
}

#Loop for all hydrographs in a single pdf

unique_events <- unique(df_events$Event)

pdf("All_Events_Inspection.pdf", width = 10, height = 7)

for (ev in unique_events) {
    df_subset <- df_events %>% filter(Event == ev)
  
    if(nrow(df_subset) > 0) {
    p <- plot_rainfall_runoff(df_subset, ev)
    print(p) #print to pdf
  }
}

dev.off()
```


#Statistics
```{r}
data %>%
  group_by(Site) %>%
  summarise(
    n = n(),
    mean_CN = mean(CN, na.rm = TRUE),
    median_CN = median(CN, na.rm = TRUE),
    sd_CN = sd(CN, na.rm = TRUE),
    cv_CN = sd_CN / mean_CN
  )

paired %>%
  group_by(Site) %>%
  summarise(
    n = n(),
    mean_CN = mean(CN, na.rm = TRUE),
    median_CN = median(CN, na.rm = TRUE),
    sd_CN = sd(CN, na.rm = TRUE),
    cv_CN = sd_CN / mean_CN
  )

all_sites %>%
  group_by(Site) %>%
  summarise(
    n = n(),
    mean_CN = mean(CN, na.rm = TRUE),
    median_CN = median(CN, na.rm = TRUE),
    sd_CN = sd(CN, na.rm = TRUE),
    cv_CN = sd_CN / mean_CN
  )

#Spearman - correlação não paramétrica
data %>%
  group_by(Site) %>%
  summarise(
    rho = cor(Rainfall_event_mm, CN, method = "spearman", use = "complete.obs")
  )

paired %>%
  group_by(Site) %>%
  summarise(
    rho = cor(Rainfall_event_mm, CN, method = "spearman", use = "complete.obs")
  )

all_sites %>%
  group_by(Site) %>%
  summarise(
    rho = cor(Rainfall_mm, CN, method = "spearman", use = "complete.obs")
  )

#Regressão linear
lm(CN ~ Rainfall_event_mm, data = data, subset = Site == "North")
lm(CN ~ Rainfall_event_mm, data = data, subset = Site == "South")

data = all_sites

#Classificar por eventos
data <- data %>%
  mutate(rain_class = cut(
    Rainfall_event_mm,
    breaks = c(0, 5, 10, 20, Inf),
    labels = c("0", "5", "10", "20")
  ))

#Comparar CN entre classes
kruskal.test(CN ~ rain_class, data = data)
kruskal.test(CN ~ Site, data = data)

#Comparar CN entre sites
kruskal.test(CN ~ interaction(Site, rain_class), data = data)

#Tamanho do efeito
cliff.delta(CN ~ Site, data = data)

#Comparar em cada classe de chuva
data %>%
  group_by(rain_class) %>%
  wilcox_test(CN ~ Site) %>%
  adjust_pvalue(method = "BH")
```

#Redwood Sites
#####All events scatterplot
```{r}
ggplot(data, aes(x = Rainfall_event_mm, y = CN,
                    color = Site, shape = Site)) +
  geom_point(size = 3, alpha = 0.8) +
  scale_color_manual(values = c("North" = "#1f78b4",
                                "South" = "#33a02c")) +
  scale_shape_manual(values = c("North" = 16,
                                "South" = 17)) +
  labs(
    x = "Rainfall (mm)",
    y = "Curve Number",
    color = "Site",
    shape = "Site",
    caption = "Based on events from 2021 onwards"
  ) +
  geom_smooth(method = "lm", se = FALSE, linewidth = 0.5) +
  theme_light() +
  theme(axis.title.y = element_text(size = 12),
        axis.title.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        axis.text.x = element_text(size = 12),
        legend.position = c(0.11, 0.15)
  )
#600 x 500
```

#####Paired events scatterplot
```{r}
ggplot(paired, aes(x = Rainfall_event_mm, y = CN,
                    color = Site, shape = Site)) +
  geom_point(size = 3, alpha = 0.8) +
  scale_color_manual(values = c("RW North" = "#1f78b4",
                                "RW South" = "#33a02c")) +
  scale_shape_manual(values = c("RW North" = 16,
                                "RW South" = 17)) +
  labs(
    x = "Rainfall (mm)",
    y = "Curve Number",
    color = "Site",
    shape = "Site",
    caption = "Based on same date events from 2021 onwards"
  ) +
  geom_smooth(method = "lm", se = FALSE, linewidth = 0.5) +
  theme_light() +
  theme(axis.title.y = element_text(size = 12),
        axis.title.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        axis.text.x = element_text(size = 12),
        legend.position = c(0.11, 0.15)
  )
```

#####All events boxplot
```{r}
ggplot(data, aes(x = Site, y = CN, fill = Site)) +
  geom_boxplot(width = 0.6, alpha = 0.6, outlier.shape = NA) +
  geom_jitter(width = 0.15, size = 2, alpha = 0.7) +
  scale_fill_manual(values = c(
    "RW North" = "#1f78b4",
    "RW South" = "#33a02c"
  )) +
  labs(y = "Curve Number",
    caption = "Based on events from 2021 onwards") +
  theme_light() +
  theme(axis.title.y = element_text(size = 12),
        axis.title.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        axis.text.x = element_text(size = 12),
        legend.position = "none"
        )
#600 x 500
```

#####Paired events boxplot
```{r}
ggplot(paired, aes(x = Site, y = CN, fill = Site)) +
  geom_boxplot(width = 0.6, alpha = 0.6, outlier.shape = NA) +
  geom_jitter(width = 0.15, size = 2, alpha = 0.7) +
  scale_fill_manual(values = c(
    "RW North" = "#1f78b4",
    "RW South" = "#33a02c"
  )) +
  labs(y = "Curve Number",
    caption = "Based on same date events from 2021 onwards") +
  theme_light() +
  theme(axis.title.y = element_text(size = 12),
        axis.title.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        axis.text.x = element_text(size = 12),
        legend.position = "none"
        )
```

#####Events prior to 2021
```{r}
ggplot(previous, aes(x = Site, y = CN, fill = Site)) +
  geom_boxplot(width = 0.6, alpha = 0.6, outlier.shape = NA) +
  geom_jitter(width = 0.15, size = 2, alpha = 0.7) +
  scale_fill_manual(values = c(
    "RW North" = "#144c73",
    "RW South" = "#20641c"
  )) +
  labs(y = "Curve Number",
    caption = "Based on events from prior to 2021") +
  theme_light() +
  theme(axis.title.y = element_text(size = 12),
        axis.title.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        axis.text.x = element_text(size = 12),
        legend.position = "none"
        )
#600 x 500
```

#Including MC Site
#####All events scatterplot
```{r}
ggplot(all_sites, aes(x = Rainfall_mm, y = CN,
                    color = Site, shape = Site)) +
  geom_point(size = 3, alpha = 0.8) +
  scale_color_manual(values = c("RW North" = "#1f78b4",
                                "RW South" = "#33a02c",
                                "MC" = "#992ca0")) +
  scale_shape_manual(values = c("RW North" = 16,
                                "RW South" = 17,
                                "MC" = 15)) +
  labs(
    x = "Rainfall (mm)",
    y = "Curve Number",
    color = "Site",
    shape = "Site",
    caption = "For RW, based on events from 2021 onwards"
  ) +
  geom_smooth(method = "lm", se = FALSE, linewidth = 0.5) +
  theme_light() +
  theme(axis.title.y = element_text(size = 12),
        axis.title.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        axis.text.x = element_text(size = 12),
        legend.position = c(0.11, 0.15)
  )
#600 x 500
```

#####All events scatterplot with CN0
```{r}
ggplot(all_sites, aes(x = Rainfall_mm, y = CN,
                    color = Site, shape = Site)) +
  geom_point(size = 3, alpha = 0.8) +
  geom_line(all_sites[order(all_sites$Rainfall_mm), ],
    mapping = aes(x = Rainfall_mm, y = CN0, linetype = "CN0"), 
    color = "black",
    linewidth = 1
  ) +
  scale_color_manual(values = c("RW North" = "#1f78b4",
                                "RW South" = "#33a02c",
                                "MC" = "#992ca0")) +
  scale_shape_manual(values = c("RW North" = 16,
                                "RW South" = 17,
                                "MC" = 15)) +
  scale_linetype_manual(values = c("CN0" = "solid")) +
  labs(
    x = "Rainfall (mm)",
    y = "Curve Number",
    color = "Site",
    shape = "Site",
    linetype = "Theoretical Model", #or set to NULL to remove the title "linetype"
    caption = "For RW, based on events from 2021 onwards"
  ) +
  theme_light() +
  theme(axis.title.y = element_text(size = 12),
        axis.title.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        axis.text.x = element_text(size = 12),
        legend.position = c(0.15, 0.25),
        legend.box = "vertical",
        legend.background = element_rect(fill = "white", color = "gray")
  )
  

#600 x 500
```

#####All events boxplot
```{r}
ggplot(all_sites, aes(x = Site, y = CN, fill = Site)) +
  geom_boxplot(width = 0.6, alpha = 0.6, outlier.shape = NA) +
  geom_jitter(width = 0.15, size = 2, alpha = 0.7) +
  scale_fill_manual(values = c(
    "RW North" = "#1f78b4",
    "RW South" = "#33a02c",
    "MC" = "#992ca0"
  )) +
  labs(y = "Curve Number",
    caption = "For RW, based on events from 2021 onwards") +
  theme_light() +
  theme(axis.title.y = element_text(size = 12),
        axis.title.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        axis.text.x = element_text(size = 12),
        legend.position = "none"
        )
#600 x 500
```

#####All events P > 5 mm boxplot
```{r}
all_sites_filter <- subset(all_sites, Rainfall_mm > 5)
```


```{r}
ggplot(all_sites_filter, aes(x = Site, y = CN, fill = Site)) +
  geom_boxplot(width = 0.6, alpha = 0.6, outlier.shape = NA) +
  geom_jitter(width = 0.15, size = 2, alpha = 0.7) +
  scale_fill_manual(values = c(
    "RW North" = "#1f78b4",
    "RW South" = "#33a02c",
    "MC" = "#992ca0"
  )) +
  labs(y = "Curve Number",
    caption = "For P > 5 mm. For RW, based on events from 2021 onwards") +
  theme_light() +
  theme(axis.title.y = element_text(size = 12),
        axis.title.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        axis.text.x = element_text(size = 12),
        legend.position = "none"
        )
#600 x 500
```
